# Generated by Django 5.1.7 on 2025-03-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
